import type { Metadata } from "next";
import "@/styles/globals.css";
import { pretendard } from "@/styles/fonts/font";
import QueryProvider from "@/components/providers/QueryProvider";
import ReduxProvider from "@/components/providers/ReduxProvider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <QueryProvider>
      <ReduxProvider>
        <html lang="ko">
          <body className={`${pretendard.variable} antialiased`}>
            {children}
          </body>
        </html>
      </ReduxProvider>
    </QueryProvider>
  );
}
